apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-controller
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-controller
  template:
    metadata:
      labels:
        app: kpack-controller
        version: 0.0.7-rc.35
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        image: gcr.io/cf-build-service-public/kpack/controller@sha256:851b5e5a5dd200310f0447d47f71fb3eefaa26da0427c96a5ce336060c30205b
        env:
        - name: BUILD_INIT_IMAGE
          value: gcr.io/cf-build-service-public/kpack/build-init@sha256:a7ecfad9791e47ab5e1a0c2f6771d9782ed19025ebdc34f6d088cb5fedb3ed2f
        - name: REBASE_IMAGE
          value: gcr.io/cf-build-service-public/kpack/rebase@sha256:1ce83aaff9073814e1c4cba3ca9496099b97361e48e77e7ad9cef9eaccf0b1c6
        - name: COMPLETION_IMAGE
          value: gcr.io/cf-build-service-public/kpack/completion@sha256:4dd97338f388b80ca5d854fd485c13ed6e37452256600a9e45c96814ab8e71ed
        - name: LIFECYCLE_IMAGE
          value: gcr.io/cf-build-service-public/kpack/lifecycle@sha256:66f723ef7452af4c5d9dd8eec3ade77adcab27df677768acb3c825165f274c87
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-webhook
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-webhook
  template:
    metadata:
      labels:
        app: kpack-webhook
        role: webhook
        version: 0.0.7-rc.35
    spec:
      serviceAccountName: webhook
      containers:
      - name: webhook
        image: gcr.io/cf-build-service-public/kpack/webhook@sha256:2e5df009b2cfbb329dad119900ff16a4e0dbe91c2edde8c6a10c119a04b68776
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace