{{- $files := .Files }}
{{- range .Values.secrets.registries }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-regsec
  annotations:
    build.pivotal.io/docker: {{ .address }}
type: kubernetes.io/basic-auth
data:
  {{ if eq .type "gcr" }}
  username: {{ "_json_key" | b64enc }}
  password: |-
    {{ $files.Get .json_file | b64enc }}
  {{ else }}
  username: {{ .username }}
  password: {{ .password }}
  {{ end }}
---
{{- end }}