{{- $files := .Files }}
{{- range .Values.secrets.git }}
apiVersion: v1
kind: Secret
{{ if eq .type "ssh" }}
metadata:
  name: {{ .name }}-gitsec
  annotations:
    build.pivotal.io/git: git@github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ $files.Get .ssh_privatekey | b64enc }}
{{ else }}
metadata:
  name: {{ .name }}-gitsec
  annotations:
    build.pivotal.io/git: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: {{ .username }}
{{ end }}
{{ if eq .type "token" }} 
  password: x-oauth-basic 
{{ else if eq .type "basic" }} 
  password: {{ .password }}
{{ end }}
---
{{- end -}}

