apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: kpack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook
  namespace: kpack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kpack.serviceAccountName" . }}
secrets:
{{- range .Values.secrets.registries }}
  - name: {{ .name }}-regsec
{{- end }}
{{- range .Values.secrets.git }}
  - name: {{ .name }}-gitsec
{{- end }}